// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract GaslessTransaction {

    // Mapping to store the nonce for each user
    mapping(address => uint256) public nonces;

    // Event emitted when a meta-transaction is successfully executed
    event MetaTransactionExecuted(address user, address relayer, bytes functionSignature);

    /**
     * @dev Executes a meta-transaction on behalf of the user.
     * @param user The address of the user who signed the transaction.
     * @param functionSignature The encoded function call that the user wants to execute.
     * @param nonce The nonce of the user to prevent replay attacks.
     * @param signature The signature generated by the user for the transaction.
     */
    function executeMetaTransaction(
        address user,
        bytes memory functionSignature,
        uint256 nonce,
        bytes memory signature
    ) public payable {
        require(nonces[user] == nonce, "Invalid nonce");
        
        // Recover the signer of the transaction
        bytes32 messageHash = getMessageHash(user, functionSignature, nonce);
        address signer = recoverSigner(messageHash, signature);

        require(signer == user, "Invalid signature");

        // Increment the user's nonce to prevent replay attacks
        nonces[user]++;

        // Execute the function
        (bool success, ) = address(this).call(functionSignature);
        require(success, "Function call failed");

        emit MetaTransactionExecuted(user, msg.sender, functionSignature);
    }

    /**
     * @dev Generates the hash of the message to be signed by the user.
     * @param user The address of the user.
     * @param functionSignature The encoded function call.
     * @param nonce The nonce for the user.
     * @return The hash of the message.
     */
    function getMessageHash(
        address user,
        bytes memory functionSignature,
        uint256 nonce
    ) public pure returns (bytes32) {
        return keccak256(abi.encodePacked(user, functionSignature, nonce));
    }

    /**
     * @dev Recovers the signer of a given hash and signature.
     * @param hash The hash of the message.
     * @param signature The signature of the hash.
     * @return The address of the signer.
     */
    function recoverSigner(bytes32 hash, bytes memory signature) public pure returns (address) {
        bytes32 ethSignedMessageHash = getEthSignedMessageHash(hash);

        (bytes32 r, bytes32 s, uint8 v) = splitSignature(signature);

        return ecrecover(ethSignedMessageHash, v, r, s);
    }

    /**
     * @dev Returns the Ethereum Signed Message hash of a given hash.
     * @param hash The hash to be signed.
     * @return The Ethereum Signed Message hash.
     */
    function getEthSignedMessageHash(bytes32 hash) public pure returns (bytes32) {
        return keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", hash));
    }

    /**
    * @dev Splits a signature into its r, s, and v components.
    * @param sig The signature to split.
    * @return r The `r` component of the signature.
    * @return s The `s` component of the signature.
    * @return v The `v` component of the signature.
    */

    function splitSignature(bytes memory sig)
        public
        pure
        returns (
            bytes32 r,
            bytes32 s,
            uint8 v
        )
    {
        require(sig.length == 65, "Invalid signature length");

        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }
    }
}
